### ISSUE TITLE
Default Settings

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#1]
Game Timer: 5:00
Arm Time: 00:10
Disarm: 00:10

**Comment by Hazesty** [comment]
Question. Do away with the manual settings as well?

**Comment by scanhead** [comment]
No, still want manual settings but just set to the counterstrike standard on startup. Im sick of changing it manually. The parameters for this may change depending on the game play irl but i want to start at this point.

**Comment by Hazesty** [comment]
Done as of V1.0.1. Rescaled the det times to 10-50 seconds in 10 second increments for fine control of the det times for testing.
