### ISSUE TITLE
Basic and Advanced Bombs (MP3 and Radio verson) Need separate code or options in menu or something

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#10]
I really want to have two versions, a basic one that can be made with the most basic hardware, maybe just on an uno board and just the button, speaker and tamper sensor. Then an advanced version that has radio announcements and MP3 samples.

**Comment by Hazesty** [comment]
Will probably finish V1.0.0 of the basic version code first. Lock in the features in the basic version and then move on.

**Comment by scanhead** [comment]
Agree. we get it as developed as we can with the minimal amount of additional hardware possible. I really just want people to be able to slap the four components together and flash the device with the code. Fastest way to get other clubs playing. I want to send these out to people asap and at the lowest cost.

**Comment by Hazesty** [comment]
Closing this issue. Will discuss advanced version later.
