### ISSUE TITLE
Game timer needs to override all states and end the game. Hard to test without game timer display

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#11]

**Comment by Hazesty** [comment]
Probably best to get a bank of seven segment displays such as : https://www.sparkfun.com/products/11441 or https://www.sparkfun.com/products/13190 for the master timer. Not sure yet, so hold that thought. Easily implemented.

**Comment by Hazesty** [comment]
Just checking: if T team with device has 10 seconds left on the clock, and device not armed (with arming time 10 seconds), T team cannot win?

**Comment by scanhead** [comment]
I think thats correct, if the game timer runs down and the bomb has not been armed or detonated then the CTs will win.

**Comment by Hazesty** [comment]
Done V1.0.1
