### ISSUE TITLE
Shorten screen changing time

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#19]
Shorten the delay between Planting/Planted and Planted/Detonated screens.  I feel like im holding my breath :)

**Comment by Hazesty** [comment]
But...but do you feel the t-tension?

**Comment by scanhead** [comment]
bomb psychology.

**Comment by Hazesty** [comment]
Ok. Changed code sequence so that the planted/defused message appears immediately before the tone playing, clearing the progress bar as fast as possible to make the next state immediately obvious. Fixed and will show up in V1.2.0

**Comment by Hazesty** [comment]
Closing as this is fixed. Delay is as low as it can be.
