### ISSUE TITLE
Unarmed bomb needs to beeb so it can be located

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#2]
An unarmed bomb needs to beeb so it can be located by T players in the event it is dropped

**Comment by Hazesty** [comment]
Agreed. Also it might be useful to have power LED indicators.

- Red for armed,
- Yellow for not yet armed
- Green for disarmed

So that the state of the bomb can be observed at a glance.

**Comment by scanhead** [comment]
I really want to keep this version as basic as possible BUT there is an LED that can be used on pin 13 i think. Its yellow and should be lit when the bomb is armed at least. This will show from a distance that if the bomb is them moved it will detonate.

**Comment by ehills** [comment]
If we're feeling lazy we could just use the led on the board itself rather
than putting another one on

**Comment by scanhead** [comment]
Yea, checked it out today and I think pin 13 with the led you're talking about is covered by the LCD sheild

**Comment by scanhead** [comment]
Just as a guide, i think it should play a tone every 15 seconds. Might be good if there was a menu adjustment for this.

**Comment by Hazesty** [comment]
Done V1.0.1.
