### ISSUE TITLE
Locatating unarmed bomb tone needs to be changed.

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#21]
The location buzzer may make the user think something is wrong with the bomb, its like an error tone. Would be good to change it to a higher pitch, I think the sound might travel further. The current tone should be used when the button is released before successful arm/disarm attempt is complete.

**Comment by Hazesty** [comment]
Checked code and found tone-notone loop that causes this distortion. A cleaner sound can easily be worked in with a higher pitch.

**Comment by Hazesty** [comment]
Change tone to higher tone (750Hz) and cleaned up the distortion.
