### ISSUE TITLE
Game timer needs permanent display during game

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#3]
Would be useful if the game timer was shown during unarmed and armed states.

**Comment by Hazesty** [comment]
see https://github.com/rubcore/TheRuddyBomb/issues/11

**Comment by scanhead** [comment]
im hoping that we can display the game countdown timer and the Bomb count down on the same screen. its a critical part of game play .I ll look into doing a format with the lcd we have. even if its just G:00:00 B:00:00. The arming and disarming screens dont really need time to arm timers on them, just the progression bar. That might save us some space.

**Comment by Hazesty** [comment]
Just double-checking, the bomb countdown timer (after armed) is how long exactly? (It's not just the end of game is it?)

**Comment by scanhead** [comment]
40 seconds

**Comment by scanhead** [comment]
every time we have played this game with the original bomb, everyone has complained it took too long. So i figure this time we develop it, we work out what the SHORTEST time a game can take and then keep increasing it until flow feels good.

**Comment by Hazesty** [comment]
Ok. I'll adjust the detonation times to around 40 seconds so that we can have it and tweak it in the field.

**Comment by Hazesty** [comment]
Done V1.0.1. 40 second det time set as default.
