### ISSUE TITLE
Detonation/Disarm Tone should be present until key press

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#5]
Detonation tone needs to be contentious until button pressed

**Comment by Hazesty** [comment]
Do you mean continuous?

**Comment by scanhead** [comment]
I mean that once the bomb detonates that the tone continues until a key is pressed so no one misses that the game is over.

**Comment by Hazesty** [comment]
What are your thoughts on a (different) continuous tone when a bomb is defused?

**Comment by scanhead** [comment]
the tone(s) do not be continual, just needs to repeat until key pressed. DTMF tone music is what i thought would be cool. ill put something into the design notes. The idea is we stick with DTMF because it is the universal keypad sound and also used for radio telemetry control if we ever get that far. There is really basic music you can make and remembering a "song" for each bomb state might be easy, ie "funky town" (look up DTMF funky town) for arming state through the speaker, and then "funky town" again over the radio when its is armed. I like the idea for happy birthday for defusing/defused.

**Comment by scanhead** [comment]
Have updated the design sheet, sorry if its been a fuck around, Stupidly though you would do all the other stuff first and i could come up with the sounds. I think we should just do a "flat line" beep to signify its dead. These are just ideas, go with something else if you think you have a better idea.

**Comment by Hazesty** [comment]
Nice sound clip choices I might add.

**Comment by scanhead** [comment]
everyone will get a laugh out of funkytown for sure :)

**Comment by scanhead** [comment]
I switched the detonation radio tones to "pop goes the weasel" as i thought it fit better

**Comment by Hazesty** [comment]
Added as per V1.1.0. Will raise new issue with customized music tones.
