### ISSUE TITLE
Tamper switch disable in config menu for if it becomes faulty

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#6]
Would be nice to be able to disable the tamper switch if its being a fuckwit.

**Comment by Hazesty** [comment]
I never realized what a fuckwit the tamper switch was being.

What are your thoughts on an honesty system regarding not moving the bomb?

**Comment by Hazesty** [comment]
Sounds good.

**Comment by Hazesty** [comment]
Ok. Thoughts on closing this topic as I've temporarily removed the tilt switch and will add the accel soon?

**Comment by scanhead** [comment]
All good man, leave it till last if you need to, it probably needs a couple of things that might take a while to figure out, like a sensitivity scale etc.
