### ISSUE TITLE
External game control button needs connecting

### ISSUE THREAD

**Issue by scanhead** [rubcore/TheRuddyBomb#8]

**Comment by Hazesty** [comment]
In order to implement the "can't do anything else whilst arming/disarming," a good idea would probably be to implement two identical buttons and put them on each side so that it's physically impossible to arm/disarm with on hand.

**Comment by scanhead** [comment]
I really want it to just be a single button interface. Id rather they could shoot while arming or disarming than lose that feature.

**Comment by scanhead** [comment]
Its simple to make things complicated but complicated to make things simple.

**Comment by Hazesty** [comment]
Done. Hardware for external button is set.
